/** HTTP status for each API error code (SDD 8.1). The key set is the single list of codes. */
export const ERROR_STATUS = {
  BAD_REQUEST: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  NO_ACCESS: 403,
  INVITATION_EMAIL_MISMATCH: 403,
  INVALID_PASSWORD: 403,
  REAUTH_REQUIRED: 403,
  NOT_SHARED: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  CONFLICT_MULTI: 409,
  ARCHIVED: 409,
  LAST_OWNER: 409,
  CANNOT_LEAVE_PERSONAL: 409,
  PERSONAL_OWNER: 409,
  ALREADY_MEMBER: 409,
  INVITATION_PENDING: 409,
  INVITATION_ALREADY_ACCEPTED: 409,
  EMAIL_TAKEN: 409,
  PASSWORD_ALREADY_SET: 409,
  DECISION_CHANGED: 409,
  DECISION_NOT_PROCEED: 409,
  NAME_TAKEN: 409,
  HAS_EMPTY_QUESTIONS: 409,
  ALREADY_LATEST: 409,
  DRAFT_EXISTS: 409,
  PUBLISHED_READ_ONLY: 409,
  INVITATION_INVALID: 410,
  PAYLOAD_TOO_LARGE: 413,
  VALIDATION_FAILED: 422,
  FACT_REQUIRES_EVIDENCE: 422,
  CONFIDENCE_REQUIRED: 422,
  INVALID_CHOICE: 422,
  QUESTION_NOT_FOUND: 422,
  PERCENT_ONLY_FOR_VARIABLE: 422,
  OUT_OF_RANGE: 422,
  NOT_EDITABLE: 422,
  INVALID_ASSIGNEE: 422,
  INVALID_STATUS: 422,
  MUST_BE_DONE_TO_SHARE: 422,
  NOT_SHAREABLE: 422,
  EMPTY_SCOPE: 422,
  NOT_IMPORTABLE: 422,
  REPLY_DEPTH: 422,
  INVALID_MENTION: 422,
  INVALID_QUESTION_KEY: 422,
  TEMPLATE_INVALID: 422,
  CANNOT_SUSPEND_SELF: 422,
  CONFIRMATION_MISMATCH: 422,
  APP_UPDATE_REQUIRED: 426,
  RATE_LIMITED: 429,
  INTERNAL: 500,
  // The Worker answers 502, 503 or 504 when it cannot reach the API; the API itself answers 503
  // when a dependency it needs is down (the database in Z2, Resend while sending an invitation).
  UPSTREAM_UNAVAILABLE: 503,
} as const;

export type ErrorCode = keyof typeof ERROR_STATUS;

export const ERROR_CODES = Object.keys(ERROR_STATUS) as ErrorCode[];

/**
 * Codes that Better Auth hooks put in the `code` of a Better Auth error. They never appear in the
 * `{ error }` envelope, so they are not part of {@link ErrorCode}.
 */
export const AUTH_HOOK_ERROR_CODES = ["INVITATION_REQUIRED", "ACCOUNT_SUSPENDED"] as const;

export type AuthHookErrorCode = (typeof AUTH_HOOK_ERROR_CODES)[number];
