import type { CostSpec, ValidationSpec } from "../validation";
import { assume, fact, log, plain, unknown, url } from "./helpers";

interface Base {
  key: string;
  ideaId: string;
  workspaceId: string;
}

/**
 * Bacolod Health Bowl (design-spec 8.2): close to the original worked example. Startup costs keep
 * three Unknown rows and one Empty row, Materials is 35% of the price, Permits is not started, and
 * three answers sit Unclassified after an AI import.
 */
export function healthBowlSpec(b: Base): ValidationSpec {
  return {
    ...b,
    templateVersion: 1,
    by: "kenji",
    createdDaysAgo: 30,
    answers: [
      assume(
        "V.01.WHO",
        "Working professionals aged 25–40 in Bacolod who pay for convenient meals.",
        "m",
      ),
      assume("V.01.WHY_THEM", "They have disposable income and little time to cook.", "l"),
      plain(
        "V.01.BEHAVIOR",
        "They order rice meals or fast food at the office and skip lunch on busy days.",
      ),
      fact(
        "V.01.PROBLEM",
        "Healthy eating is hard to sustain because planning, cooking and portion control take time.",
        [log("h2"), log("h3")],
      ),
      assume("V.01.FREQUENCY", "Every working day.", "m"),
      plain(
        "V.01.SWITCHING",
        "Clear calories and macros on every bowl, and a price close to a fast-food meal.",
      ),
      unknown("V.01.PAYMENT", "We do not know how much more than ₱150 they will pay."),
      assume("V.02.CATEGORY", "Healthy fast-casual meals", "m"),
      assume("V.02.OCEAN", "Red", "m"),
      assume(
        "V.02.WHY",
        "Several salad and rice-bowl shops already serve the same customers.",
        "m",
      ),
      plain("V.02.DRIVERS", "Gym culture, remote workers and delivery apps."),
      fact("V.02.RED_1", "Two salad shops and a bowl cafe near the business district.", [
        log("h1"),
      ]),
      assume("V.02.RED_2", "Loyal lunch crowds and fast service.", "l"),
      assume("V.10.WHY_WORK", "Existing shops prove people buy healthy lunches.", "m"),
      unknown("V.10.BIGGEST_UNKNOWN", "Whether customers repeat at a ₱220 price."),
    ],
    research: [
      {
        id: "h1",
        daysAgo: 27,
        topic: "Bowl prices at two cafes",
        observation: "Healthy bowls cost ₱240–₱260 near the business district.",
        sourceType: "price_check",
        supports: ["local_price"],
        by: "kenji",
      },
      {
        id: "h2",
        daysAgo: 25,
        topic: "Lunch rush at a salad shop",
        observation: "A queue of twelve at 12:15 and two shelves of bowls sold out by 12:40.",
        sourceType: "store_observation",
        supports: ["demand_signal"],
        by: "kenji",
      },
      {
        id: "h3",
        daysAgo: 24,
        topic: "Reviews mention few healthy choices",
        observation: "Reviews of nearby restaurants say there is nothing light for lunch.",
        sourceType: "google_maps_reviews",
        supports: ["demand_signal"],
        by: "paolo",
      },
      {
        id: "h4",
        daysAgo: 22,
        topic: "Nutrition labels on competitor menus",
        observation: "None of the three nearest shops prints calories on the menu.",
        sourceType: "website",
        supports: [],
        by: "kenji",
      },
      {
        id: "h5",
        daysAgo: 20,
        topic: "Local fitness groups on Facebook",
        observation: "Two groups with over 3,000 members share meal-prep tips.",
        sourceType: "social_media",
        supports: [],
        by: "kenji",
      },
    ],
    competitors: [
      {
        name: "Salad Station",
        type: "direct",
        targetCustomer: "Office workers",
        offering: "Build-your-own salad bowls",
        typicalPrice: 240,
        priceNote: "per bowl",
        strength: "Prime location",
        weakness: "No nutrition information",
        whyChosen: "Fast and fresh",
        whySurvive: "Lunch rush volume",
      },
      {
        name: "Bowl & Co",
        type: "direct",
        targetCustomer: "Students and young professionals",
        offering: "Rice and protein bowls",
        typicalPrice: 260,
        priceNote: "per bowl",
        strength: "Filling portions",
        weakness: "Small menu",
        whyChosen: "Taste",
        whySurvive: "Loyal regulars",
      },
      {
        name: "Fast-food chains",
        type: "indirect",
        targetCustomer: "Everyone",
        offering: "Burgers and chicken meals",
        typicalPrice: null,
        strength: "Price and speed",
        weakness: "Not seen as healthy",
        whyChosen: "Habit",
        whySurvive: "Scale",
      },
      {
        name: "Home meal prep",
        type: "substitute",
        targetCustomer: "People who cook on Sundays",
        offering: "Packed lunches from home",
        typicalPrice: null,
        strength: "Cheap",
        weakness: "Takes planning",
        whyChosen: "Control over ingredients",
        whySurvive: "Always available",
      },
    ],
    costs: {
      "initial.equipment": {
        amount: 60000,
        fau: "fact",
        evidence: [url("https://example.com/suppliers/kitchen-quote", "Kitchen equipment quote")],
        canReduce: "partly",
      },
      "initial.renovation": {
        amount: 30000,
        fau: "assumption",
        confidence: "medium",
        canReduce: "yes",
      },
      "initial.lease_deposit": {
        amount: 30000,
        fau: "assumption",
        confidence: "high",
        canReduce: "no",
      },
      "initial.permits": { fau: "unknown" },
      "initial.inventory": { fau: "unknown" },
      "initial.branding": { amount: 10000, fau: "assumption", confidence: "low", canReduce: "yes" },
      "initial.launch_marketing": {
        amount: 15000,
        fau: "assumption",
        confidence: "medium",
        canReduce: "partly",
      },
      "initial.tech_setup": { fau: "unknown" },
      "initial.other": { amount: 0, fau: "assumption", confidence: "low" },
      "monthly.rent": { amount: 15000, fau: "assumption", confidence: "medium" },
      "monthly.salaries": { amount: 24000, fau: "assumption", confidence: "medium" },
      "monthly.utilities": { amount: 4500, fau: "assumption", confidence: "medium" },
      "monthly.internet": { amount: 1500, fau: "assumption", confidence: "high" },
      "monthly.accounting": { amount: 2000, fau: "assumption", confidence: "high" },
      "monthly.marketing": { amount: 3000, fau: "assumption", confidence: "medium" },
      "monthly.insurance": { amount: 0, fau: "assumption", confidence: "low" },
      "monthly.other": { amount: 0, fau: "assumption", confidence: "low" },
      "variable.materials": { percent: 0.35, fau: "assumption", confidence: "medium" },
      "variable.packaging": { amount: 12, fau: "assumption", confidence: "medium" },
      "variable.delivery": { amount: 15, fau: "assumption", confidence: "low" },
    },
    econ: {
      selling_price: { value: 220, fau: "assumption", confidence: "medium" },
      units_conservative: { value: 15, fau: "assumption", confidence: "low" },
      units_expected: { value: 25, fau: "assumption", confidence: "medium" },
      units_strong: { value: 35, fau: "assumption", confidence: "low" },
      units_capacity: { value: 45, fau: "assumption", confidence: "medium" },
    },
    assumptions: [
      {
        statement: "Customers repeat at ₱220 a bowl.",
        whyBelieve: "Competitors charge ₱240–₱260.",
        evidenceNote: "Price checks",
        confidence: "medium",
        disproveCondition: "Repeat rate below 30% in the first month.",
        nextCheck: "Sell sample bowls at two offices.",
      },
      {
        statement: "Startup cost stays near ₱145,000 once the Unknown rows are priced.",
        whyBelieve: "Equipment is quoted; the rest are estimates.",
        evidenceNote: "Kitchen quote",
        confidence: "low",
        disproveCondition: "Permits and inventory add more than ₱40,000.",
        nextCheck: "Price permits and first inventory.",
      },
    ],
    risks: [
      {
        statement: "Food cost rises above 35% of the price.",
        probability: "medium",
        impact: "high",
        whyMatters: "Contribution per bowl would fall below ₱100.",
        mitigation: "Fix the menu to four bowls and buy in bulk.",
        howToValidate: "Cost five test batches.",
      },
      {
        statement: "Permits take longer than planned.",
        probability: "medium",
        impact: "medium",
        whyMatters: "Rent starts before sales.",
        mitigation: "Apply before signing the lease.",
        howToValidate: "Ask City Hall for the timeline.",
      },
    ],
  };
}

/** Student Study Café (design-spec 8.2): a validation complete enough to have reached launch prep. */
export function studyCafeSpec(b: Base): ValidationSpec {
  const costs: Record<string, CostSpec> = {
    "initial.equipment": {
      amount: 80000,
      fau: "fact",
      evidence: [url("https://example.com/suppliers/furniture-quote", "Desks and chairs quote")],
      canReduce: "partly",
    },
    "initial.renovation": {
      amount: 120000,
      fau: "assumption",
      confidence: "medium",
      canReduce: "partly",
    },
    "initial.lease_deposit": {
      amount: 60000,
      fau: "assumption",
      confidence: "high",
      canReduce: "no",
    },
    "initial.permits": { amount: 12000, fau: "fact", evidence: [log("s2")], canReduce: "no" },
    "initial.inventory": {
      amount: 20000,
      fau: "assumption",
      confidence: "medium",
      canReduce: "yes",
    },
    "initial.branding": {
      amount: 15000,
      fau: "assumption",
      confidence: "medium",
      canReduce: "yes",
    },
    "initial.launch_marketing": {
      amount: 15000,
      fau: "assumption",
      confidence: "medium",
      canReduce: "partly",
    },
    "initial.tech_setup": {
      amount: 25000,
      fau: "assumption",
      confidence: "medium",
      canReduce: "partly",
    },
    "initial.working_capital": {
      amount: 80000,
      fau: "assumption",
      confidence: "medium",
      canReduce: "no",
    },
    "initial.other": { amount: 0, fau: "assumption", confidence: "low" },
    "monthly.rent": { amount: 30000, fau: "assumption", confidence: "high" },
    "monthly.salaries": { amount: 40000, fau: "assumption", confidence: "medium" },
    "monthly.utilities": { amount: 9000, fau: "assumption", confidence: "medium" },
    "monthly.internet": { amount: 2500, fau: "assumption", confidence: "high" },
    "monthly.accounting": { amount: 3000, fau: "assumption", confidence: "high" },
    "monthly.marketing": { amount: 4000, fau: "assumption", confidence: "medium" },
    "monthly.insurance": { amount: 1500, fau: "assumption", confidence: "medium" },
    "monthly.other": { amount: 0, fau: "assumption", confidence: "low" },
    "variable.materials": { amount: 35, fau: "assumption", confidence: "medium" },
    "variable.packaging": { amount: 5, fau: "assumption", confidence: "medium" },
    "variable.payment_fee": { percent: 0.02, fau: "assumption", confidence: "high" },
    "variable.delivery": { amount: 0, fau: "assumption", confidence: "high" },
    "variable.labor": { amount: 0, fau: "assumption", confidence: "medium" },
    "variable.other": { amount: 0, fau: "assumption", confidence: "low" },
  };
  return {
    ...b,
    templateVersion: 1,
    by: "paolo",
    createdDaysAgo: 90,
    answers: [
      assume(
        "V.01.WHO",
        "University students in Bacolod who need a quiet place to study for hours.",
        "m",
      ),
      fact("V.01.PROBLEM", "Dorms and cafes are noisy, and libraries close early.", [log("s3")]),
      assume(
        "V.01.PAYMENT",
        "They pay for a reliable seat with power outlets and fast Wi-Fi.",
        "m",
      ),
      assume("V.02.CATEGORY", "Paid study space", "m"),
      assume("V.02.OCEAN", "Blue", "m"),
      assume("V.02.WHY", "Cafes sell coffee, not quiet seats by the hour.", "m"),
      assume("V.02.BLUE_1", "Quiet seats with outlets near campuses.", "m"),
      assume("V.02.BLUE_2", "Cafe owners fear empty tables from long stays.", "l"),
      fact("V.02.BLUE_3", "Students queue for library seats before exams.", [log("s3")]),
      assume(
        "V.08.WORTH",
        "Payback within two years is acceptable for a steady student market.",
        "m",
      ),
      assume(
        "V.10.WHY_WORK",
        "Exam seasons fill every seat and students already pay for coffee.",
        "m",
      ),
      assume("V.10.BIGGEST_RISK", "Demand drops during school breaks.", "m"),
    ],
    research: [
      {
        id: "s1",
        daysAgo: 85,
        topic: "Hourly rates at coworking spaces",
        observation: "Two spaces charge ₱120–₱180 an hour for a desk.",
        sourceType: "price_check",
        supports: ["local_price"],
        by: "paolo",
      },
      {
        id: "s2",
        daysAgo: 83,
        topic: "Permits for a cafe with seating",
        observation:
          "A mayor's permit and a sanitary permit are required; fees total about ₱12,000.",
        sourceType: "public_data",
        supports: ["permits"],
        by: "paolo",
      },
      {
        id: "s3",
        daysAgo: 80,
        topic: "Library queue before midterms",
        observation:
          "Thirty students waited for seats at the university library on a weekday evening.",
        sourceType: "store_observation",
        supports: ["demand_signal"],
        by: "kenji",
      },
      {
        id: "s4",
        daysAgo: 78,
        topic: "Student groups asking for quiet spaces",
        observation: "A student page posted three requests for quiet study spots this month.",
        sourceType: "social_media",
        supports: [],
        by: "paolo",
      },
    ],
    competitors: [
      {
        name: "Campus library",
        type: "substitute",
        targetCustomer: "Enrolled students",
        offering: "Free seats until 8 pm",
        typicalPrice: 0,
        strength: "Free",
        weakness: "Full before exams; closes early",
        whyChosen: "No cost",
        whySurvive: "Funded by the school",
      },
      {
        name: "Downtown coworking space",
        type: "direct",
        targetCustomer: "Freelancers",
        offering: "Hourly desks",
        typicalPrice: 150,
        priceNote: "per hour",
        strength: "Quiet",
        weakness: "Far from campuses",
        whyChosen: "Reliable Wi-Fi",
        whySurvive: "Monthly members",
      },
      {
        name: "Specialty coffee shop",
        type: "indirect",
        targetCustomer: "Students and remote workers",
        offering: "Coffee with open seating",
        typicalPrice: 140,
        priceNote: "per drink",
        strength: "Atmosphere",
        weakness: "Noisy; no guaranteed seat",
        whyChosen: "Close to campus",
        whySurvive: "Drink margins",
      },
    ],
    costs,
    econ: {
      selling_price: { value: 150, fau: "assumption", confidence: "medium" },
      operating_days: { value: 26, fau: "assumption", confidence: "high" },
      units_conservative: { value: 20, fau: "assumption", confidence: "low" },
      units_expected: { value: 40, fau: "assumption", confidence: "medium" },
      units_strong: { value: 55, fau: "assumption", confidence: "low" },
      units_capacity: { value: 70, fau: "assumption", confidence: "high" },
    },
    assumptions: [
      {
        statement: "Students pay ₱150 for a three-hour seat.",
        whyBelieve: "Coworking desks charge ₱120–₱180 an hour.",
        evidenceNote: "Price checks",
        confidence: "medium",
        disproveCondition: "Fewer than 20 paid seats a day in the first month.",
        nextCheck: "Run a two-week trial with a loyalty card.",
      },
    ],
    risks: [
      {
        statement: "Demand drops during school breaks.",
        probability: "high",
        impact: "medium",
        whyMatters: "Rent and salaries continue.",
        mitigation: "Offer monthly passes and freelancer hours.",
        howToValidate: "Track visits per week.",
      },
    ],
  };
}

/** Laundry Pickup (design-spec 8.2): price ₱60/kg against ₱75/kg of variable cost. */
export function laundrySpec(b: Base): ValidationSpec {
  return {
    ...b,
    templateVersion: 1,
    by: "paolo",
    createdDaysAgo: 45,
    answers: [
      assume("V.01.WHO", "Apartment dwellers in Bacolod who have no washing machine.", "m"),
      assume("V.01.PROBLEM", "Washing by hand takes hours and laundromats are far.", "m"),
      assume("V.01.PAYMENT", "They pay a small premium for pickup and delivery.", "l"),
      fact(
        "V.10.WHY_FAIL",
        "Delivery costs ₱40 per kg at low volume, which is more than the margin at ₱60 per kg.",
        [log("l1")],
      ),
      assume("V.10.BIGGEST_RISK", "Every kilo loses money at the current price.", "h"),
    ],
    research: [
      {
        id: "l1",
        daysAgo: 40,
        topic: "Laundry shop prices",
        observation: "Shops charge ₱55–₱70 per kilo, with free delivery over five kilos.",
        sourceType: "price_check",
        supports: ["local_price"],
        by: "paolo",
      },
      {
        id: "l2",
        daysAgo: 38,
        topic: "Apartment residents asking for laundry help",
        observation: "Five posts in a housing group ask for a laundry service.",
        sourceType: "social_media",
        supports: ["demand_signal"],
        by: "paolo",
      },
    ],
    competitors: [
      {
        name: "Neighborhood laundry shop",
        type: "direct",
        targetCustomer: "Nearby residents",
        offering: "Wash and fold by the kilo",
        typicalPrice: 70,
        priceNote: "per kg",
        strength: "Free delivery over five kilos",
        weakness: "Slow turnaround",
        whyChosen: "Close by",
        whySurvive: "Low rent",
      },
      {
        name: "Self-service laundromat",
        type: "indirect",
        targetCustomer: "Students",
        offering: "Coin machines",
        typicalPrice: 55,
        priceNote: "per kg",
        strength: "Cheap",
        weakness: "Customers must wait",
        whyChosen: "Price",
        whySurvive: "No labor",
      },
    ],
    costs: {
      "initial.equipment": {
        amount: 45000,
        fau: "assumption",
        confidence: "medium",
        canReduce: "partly",
      },
      "monthly.rent": { amount: 8000, fau: "assumption", confidence: "medium" },
      "monthly.salaries": { amount: 12000, fau: "assumption", confidence: "medium" },
      "monthly.utilities": { amount: 5000, fau: "assumption", confidence: "medium" },
      "variable.materials": { amount: 20, fau: "assumption", confidence: "medium" },
      "variable.delivery": { amount: 40, fau: "assumption", confidence: "medium" },
      "variable.labor": { amount: 15, fau: "assumption", confidence: "low" },
    },
    econ: {
      selling_price: { value: 60, fau: "assumption", confidence: "medium" },
      operating_days: { value: 26, fau: "assumption", confidence: "high" },
      units_conservative: { value: 40, fau: "assumption", confidence: "low" },
      units_expected: { value: 80, fau: "assumption", confidence: "low" },
      units_strong: { value: 120, fau: "assumption", confidence: "low" },
      units_capacity: { value: 200, fau: "assumption", confidence: "medium" },
    },
    assumptions: [],
    risks: [
      {
        statement: "Delivery cost per kilo cannot fall below ₱40.",
        probability: "high",
        impact: "high",
        whyMatters: "The contribution margin stays negative.",
        mitigation: "Charge a delivery fee or batch routes.",
        howToValidate: "Time five pickup routes.",
      },
    ],
  };
}

/** Mobile Bike Repair (design-spec 8.2): almost empty, on template v2. */
export function bikeRepairSpec(b: Base): ValidationSpec {
  return {
    ...b,
    templateVersion: 2,
    by: "ana",
    createdDaysAgo: 4,
    answers: [
      assume("V.01.WHO", "Commuters who ride to work and cannot visit a shop in the daytime.", "l"),
      plain("V.01.PROBLEM", "A flat tire means walking the bike to a shop."),
    ],
    research: [],
    competitors: [],
    costs: {},
    econ: {},
    assumptions: [],
    risks: [],
  };
}
