/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthedFrameRouteImport } from './routes/_authed/_frame'
import { Route as AuthedWelcomeRouteImport } from './routes/_authed/welcome'
import { Route as DevComponentsRouteImport } from './routes/dev.components'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthedFrameAccountRouteImport } from './routes/_authed/_frame/account'
import { Route as AuthedFrameAdminRouteImport } from './routes/_authed/_frame/admin'
import { Route as AuthedFrameNotificationsRouteImport } from './routes/_authed/_frame/notifications'
import { Route as AuthedFrameAdminUsersRouteImport } from './routes/_authed/_frame/admin.users'
import { Route as AuthedFrameWWorkspaceIdRouteImport } from './routes/_authed/_frame/w.$workspaceId'
import { Route as AuthedFrameWWorkspaceIdIndexRouteImport } from './routes/_authed/_frame/w.$workspaceId.index'
import { Route as AuthedFrameWWorkspaceIdDecisionsRouteImport } from './routes/_authed/_frame/w.$workspaceId.decisions'
import { Route as AuthedFrameWWorkspaceIdIdeasRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas'
import { Route as AuthedFrameWWorkspaceIdSelfAnalysisRouteImport } from './routes/_authed/_frame/w.$workspaceId.self-analysis'
import { Route as AuthedFrameWWorkspaceIdSettingsRouteImport } from './routes/_authed/_frame/w.$workspaceId.settings'
import { Route as AuthedFrameWWorkspaceIdTeamRouteImport } from './routes/_authed/_frame/w.$workspaceId.team'
import { Route as AuthedFrameWWorkspaceIdAiExportRouteImport } from './routes/_authed/_frame/w.$workspaceId.ai.export'
import { Route as AuthedFrameWWorkspaceIdAiImportRouteImport } from './routes/_authed/_frame/w.$workspaceId.ai.import'
import { Route as AuthedFrameWWorkspaceIdIdeasIndexRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.index'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId'
import { Route as AuthedFrameWWorkspaceIdSelfAnalysisIndexRouteImport } from './routes/_authed/_frame/w.$workspaceId.self-analysis.index'
import { Route as AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRouteImport } from './routes/_authed/_frame/w.$workspaceId.self-analysis.$sectionKey'
import { Route as AuthedFrameWWorkspaceIdTeamIndexRouteImport } from './routes/_authed/_frame/w.$workspaceId.team.index'
import { Route as AuthedFrameWWorkspaceIdTeamUserIdRouteImport } from './routes/_authed/_frame/w.$workspaceId.team.$userId'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.index'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.assumptions'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.competitors'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.costs'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.decide'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.economics'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.research'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.plans.$planId'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.questions.$sectionKey'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.plans.$planId.index'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.plans.$planId.execution'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.plans.$planId.pitch'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.plans.$planId.items.$itemNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedFrameRoute = AuthedFrameRouteImport.update({
  id: '/_frame',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWelcomeRoute = AuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedRoute,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedFrameAccountRoute = AuthedFrameAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedFrameRoute,
} as any)
const AuthedFrameAdminRoute = AuthedFrameAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedFrameRoute,
} as any)
const AuthedFrameNotificationsRoute =
  AuthedFrameNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedFrameRoute,
  } as any)
const AuthedFrameAdminUsersRoute = AuthedFrameAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedFrameAdminRoute,
} as any)
const AuthedFrameWWorkspaceIdRoute = AuthedFrameWWorkspaceIdRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => AuthedFrameRoute,
} as any)
const AuthedFrameWWorkspaceIdIndexRoute =
  AuthedFrameWWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdDecisionsRoute =
  AuthedFrameWWorkspaceIdDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasRoute =
  AuthedFrameWWorkspaceIdIdeasRouteImport.update({
    id: '/ideas',
    path: '/ideas',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdSelfAnalysisRoute =
  AuthedFrameWWorkspaceIdSelfAnalysisRouteImport.update({
    id: '/self-analysis',
    path: '/self-analysis',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdSettingsRoute =
  AuthedFrameWWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdTeamRoute =
  AuthedFrameWWorkspaceIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdAiExportRoute =
  AuthedFrameWWorkspaceIdAiExportRouteImport.update({
    id: '/ai/export',
    path: '/ai/export',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdAiImportRoute =
  AuthedFrameWWorkspaceIdAiImportRouteImport.update({
    id: '/ai/import',
    path: '/ai/import',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIndexRoute =
  AuthedFrameWWorkspaceIdIdeasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdRouteImport.update({
    id: '/$ideaId',
    path: '/$ideaId',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasRoute,
  } as any)
const AuthedFrameWWorkspaceIdSelfAnalysisIndexRoute =
  AuthedFrameWWorkspaceIdSelfAnalysisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFrameWWorkspaceIdSelfAnalysisRoute,
  } as any)
const AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRoute =
  AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRouteImport.update({
    id: '/$sectionKey',
    path: '/$sectionKey',
    getParentRoute: () => AuthedFrameWWorkspaceIdSelfAnalysisRoute,
  } as any)
const AuthedFrameWWorkspaceIdTeamIndexRoute =
  AuthedFrameWWorkspaceIdTeamIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFrameWWorkspaceIdTeamRoute,
  } as any)
const AuthedFrameWWorkspaceIdTeamUserIdRoute =
  AuthedFrameWWorkspaceIdTeamUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthedFrameWWorkspaceIdTeamRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRouteImport.update({
    id: '/assumptions',
    path: '/assumptions',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRouteImport.update({
    id: '/costs',
    path: '/costs',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRouteImport.update({
    id: '/decide',
    path: '/decide',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRouteImport.update({
    id: '/economics',
    path: '/economics',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteImport.update({
    id: '/plans/$planId',
    path: '/plans/$planId',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRouteImport.update({
    id: '/questions/$sectionKey',
    path: '/questions/$sectionKey',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRouteImport.update({
    id: '/execution',
    path: '/execution',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRouteImport.update({
    id: '/pitch',
    path: '/pitch',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRouteImport.update({
    id: '/items/$itemNo',
    path: '/items/$itemNo',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/dev/components': typeof DevComponentsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/account': typeof AuthedFrameAccountRoute
  '/admin': typeof AuthedFrameAdminRouteWithChildren
  '/notifications': typeof AuthedFrameNotificationsRoute
  '/admin/users': typeof AuthedFrameAdminUsersRoute
  '/w/$workspaceId': typeof AuthedFrameWWorkspaceIdRouteWithChildren
  '/w/$workspaceId/decisions': typeof AuthedFrameWWorkspaceIdDecisionsRoute
  '/w/$workspaceId/ideas': typeof AuthedFrameWWorkspaceIdIdeasRouteWithChildren
  '/w/$workspaceId/self-analysis': typeof AuthedFrameWWorkspaceIdSelfAnalysisRouteWithChildren
  '/w/$workspaceId/settings': typeof AuthedFrameWWorkspaceIdSettingsRoute
  '/w/$workspaceId/team': typeof AuthedFrameWWorkspaceIdTeamRouteWithChildren
  '/w/$workspaceId/': typeof AuthedFrameWWorkspaceIdIndexRoute
  '/w/$workspaceId/ai/export': typeof AuthedFrameWWorkspaceIdAiExportRoute
  '/w/$workspaceId/ai/import': typeof AuthedFrameWWorkspaceIdAiImportRoute
  '/w/$workspaceId/ideas/$ideaId': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren
  '/w/$workspaceId/self-analysis/$sectionKey': typeof AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRoute
  '/w/$workspaceId/team/$userId': typeof AuthedFrameWWorkspaceIdTeamUserIdRoute
  '/w/$workspaceId/ideas/': typeof AuthedFrameWWorkspaceIdIdeasIndexRoute
  '/w/$workspaceId/self-analysis/': typeof AuthedFrameWWorkspaceIdSelfAnalysisIndexRoute
  '/w/$workspaceId/team/': typeof AuthedFrameWWorkspaceIdTeamIndexRoute
  '/w/$workspaceId/ideas/$ideaId/assumptions': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRoute
  '/w/$workspaceId/ideas/$ideaId/competitors': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRoute
  '/w/$workspaceId/ideas/$ideaId/costs': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute
  '/w/$workspaceId/ideas/$ideaId/decide': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute
  '/w/$workspaceId/ideas/$ideaId/economics': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute
  '/w/$workspaceId/ideas/$ideaId/research': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRoute
  '/w/$workspaceId/ideas/$ideaId/': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute
  '/w/$workspaceId/ideas/$ideaId/plans/$planId': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteWithChildren
  '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute
  '/w/$workspaceId/ideas/$ideaId/plans/$planId/execution': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRoute
  '/w/$workspaceId/ideas/$ideaId/plans/$planId/pitch': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRoute
  '/w/$workspaceId/ideas/$ideaId/plans/$planId/': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRoute
  '/w/$workspaceId/ideas/$ideaId/plans/$planId/items/$itemNo': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/dev/components': typeof DevComponentsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/account': typeof AuthedFrameAccountRoute
  '/admin': typeof AuthedFrameAdminRouteWithChildren
  '/notifications': typeof AuthedFrameNotificationsRoute
  '/admin/users': typeof AuthedFrameAdminUsersRoute
  '/w/$workspaceId/decisions': typeof AuthedFrameWWorkspaceIdDecisionsRoute
  '/w/$workspaceId/settings': typeof AuthedFrameWWorkspaceIdSettingsRoute
  '/w/$workspaceId': typeof AuthedFrameWWorkspaceIdIndexRoute
  '/w/$workspaceId/ai/export': typeof AuthedFrameWWorkspaceIdAiExportRoute
  '/w/$workspaceId/ai/import': typeof AuthedFrameWWorkspaceIdAiImportRoute
  '/w/$workspaceId/self-analysis/$sectionKey': typeof AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRoute
  '/w/$workspaceId/team/$userId': typeof AuthedFrameWWorkspaceIdTeamUserIdRoute
  '/w/$workspaceId/ideas': typeof AuthedFrameWWorkspaceIdIdeasIndexRoute
  '/w/$workspaceId/self-analysis': typeof AuthedFrameWWorkspaceIdSelfAnalysisIndexRoute
  '/w/$workspaceId/team': typeof AuthedFrameWWorkspaceIdTeamIndexRoute
  '/w/$workspaceId/ideas/$ideaId/assumptions': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRoute
  '/w/$workspaceId/ideas/$ideaId/competitors': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRoute
  '/w/$workspaceId/ideas/$ideaId/costs': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute
  '/w/$workspaceId/ideas/$ideaId/decide': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute
  '/w/$workspaceId/ideas/$ideaId/economics': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute
  '/w/$workspaceId/ideas/$ideaId/research': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRoute
  '/w/$workspaceId/ideas/$ideaId': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute
  '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute
  '/w/$workspaceId/ideas/$ideaId/plans/$planId/execution': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRoute
  '/w/$workspaceId/ideas/$ideaId/plans/$planId/pitch': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRoute
  '/w/$workspaceId/ideas/$ideaId/plans/$planId': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRoute
  '/w/$workspaceId/ideas/$ideaId/plans/$planId/items/$itemNo': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/_frame': typeof AuthedFrameRouteWithChildren
  '/_authed/welcome': typeof AuthedWelcomeRoute
  '/dev/components': typeof DevComponentsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authed/_frame/account': typeof AuthedFrameAccountRoute
  '/_authed/_frame/admin': typeof AuthedFrameAdminRouteWithChildren
  '/_authed/_frame/notifications': typeof AuthedFrameNotificationsRoute
  '/_authed/_frame/admin/users': typeof AuthedFrameAdminUsersRoute
  '/_authed/_frame/w/$workspaceId': typeof AuthedFrameWWorkspaceIdRouteWithChildren
  '/_authed/_frame/w/$workspaceId/decisions': typeof AuthedFrameWWorkspaceIdDecisionsRoute
  '/_authed/_frame/w/$workspaceId/ideas': typeof AuthedFrameWWorkspaceIdIdeasRouteWithChildren
  '/_authed/_frame/w/$workspaceId/self-analysis': typeof AuthedFrameWWorkspaceIdSelfAnalysisRouteWithChildren
  '/_authed/_frame/w/$workspaceId/settings': typeof AuthedFrameWWorkspaceIdSettingsRoute
  '/_authed/_frame/w/$workspaceId/team': typeof AuthedFrameWWorkspaceIdTeamRouteWithChildren
  '/_authed/_frame/w/$workspaceId/': typeof AuthedFrameWWorkspaceIdIndexRoute
  '/_authed/_frame/w/$workspaceId/ai/export': typeof AuthedFrameWWorkspaceIdAiExportRoute
  '/_authed/_frame/w/$workspaceId/ai/import': typeof AuthedFrameWWorkspaceIdAiImportRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren
  '/_authed/_frame/w/$workspaceId/self-analysis/$sectionKey': typeof AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRoute
  '/_authed/_frame/w/$workspaceId/team/$userId': typeof AuthedFrameWWorkspaceIdTeamUserIdRoute
  '/_authed/_frame/w/$workspaceId/ideas/': typeof AuthedFrameWWorkspaceIdIdeasIndexRoute
  '/_authed/_frame/w/$workspaceId/self-analysis/': typeof AuthedFrameWWorkspaceIdSelfAnalysisIndexRoute
  '/_authed/_frame/w/$workspaceId/team/': typeof AuthedFrameWWorkspaceIdTeamIndexRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/assumptions': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/competitors': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/costs': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/decide': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/economics': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/research': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteWithChildren
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/questions/$sectionKey': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/execution': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/pitch': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/items/$itemNo': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/welcome'
    | '/dev/components'
    | '/invite/$token'
    | '/account'
    | '/admin'
    | '/notifications'
    | '/admin/users'
    | '/w/$workspaceId'
    | '/w/$workspaceId/decisions'
    | '/w/$workspaceId/ideas'
    | '/w/$workspaceId/self-analysis'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/team'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/ai/export'
    | '/w/$workspaceId/ai/import'
    | '/w/$workspaceId/ideas/$ideaId'
    | '/w/$workspaceId/self-analysis/$sectionKey'
    | '/w/$workspaceId/team/$userId'
    | '/w/$workspaceId/ideas/'
    | '/w/$workspaceId/self-analysis/'
    | '/w/$workspaceId/team/'
    | '/w/$workspaceId/ideas/$ideaId/assumptions'
    | '/w/$workspaceId/ideas/$ideaId/competitors'
    | '/w/$workspaceId/ideas/$ideaId/costs'
    | '/w/$workspaceId/ideas/$ideaId/decide'
    | '/w/$workspaceId/ideas/$ideaId/economics'
    | '/w/$workspaceId/ideas/$ideaId/research'
    | '/w/$workspaceId/ideas/$ideaId/'
    | '/w/$workspaceId/ideas/$ideaId/plans/$planId'
    | '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
    | '/w/$workspaceId/ideas/$ideaId/plans/$planId/execution'
    | '/w/$workspaceId/ideas/$ideaId/plans/$planId/pitch'
    | '/w/$workspaceId/ideas/$ideaId/plans/$planId/'
    | '/w/$workspaceId/ideas/$ideaId/plans/$planId/items/$itemNo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/welcome'
    | '/dev/components'
    | '/invite/$token'
    | '/account'
    | '/admin'
    | '/notifications'
    | '/admin/users'
    | '/w/$workspaceId/decisions'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId'
    | '/w/$workspaceId/ai/export'
    | '/w/$workspaceId/ai/import'
    | '/w/$workspaceId/self-analysis/$sectionKey'
    | '/w/$workspaceId/team/$userId'
    | '/w/$workspaceId/ideas'
    | '/w/$workspaceId/self-analysis'
    | '/w/$workspaceId/team'
    | '/w/$workspaceId/ideas/$ideaId/assumptions'
    | '/w/$workspaceId/ideas/$ideaId/competitors'
    | '/w/$workspaceId/ideas/$ideaId/costs'
    | '/w/$workspaceId/ideas/$ideaId/decide'
    | '/w/$workspaceId/ideas/$ideaId/economics'
    | '/w/$workspaceId/ideas/$ideaId/research'
    | '/w/$workspaceId/ideas/$ideaId'
    | '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
    | '/w/$workspaceId/ideas/$ideaId/plans/$planId/execution'
    | '/w/$workspaceId/ideas/$ideaId/plans/$planId/pitch'
    | '/w/$workspaceId/ideas/$ideaId/plans/$planId'
    | '/w/$workspaceId/ideas/$ideaId/plans/$planId/items/$itemNo'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authed/_frame'
    | '/_authed/welcome'
    | '/dev/components'
    | '/invite/$token'
    | '/_authed/_frame/account'
    | '/_authed/_frame/admin'
    | '/_authed/_frame/notifications'
    | '/_authed/_frame/admin/users'
    | '/_authed/_frame/w/$workspaceId'
    | '/_authed/_frame/w/$workspaceId/decisions'
    | '/_authed/_frame/w/$workspaceId/ideas'
    | '/_authed/_frame/w/$workspaceId/self-analysis'
    | '/_authed/_frame/w/$workspaceId/settings'
    | '/_authed/_frame/w/$workspaceId/team'
    | '/_authed/_frame/w/$workspaceId/'
    | '/_authed/_frame/w/$workspaceId/ai/export'
    | '/_authed/_frame/w/$workspaceId/ai/import'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId'
    | '/_authed/_frame/w/$workspaceId/self-analysis/$sectionKey'
    | '/_authed/_frame/w/$workspaceId/team/$userId'
    | '/_authed/_frame/w/$workspaceId/ideas/'
    | '/_authed/_frame/w/$workspaceId/self-analysis/'
    | '/_authed/_frame/w/$workspaceId/team/'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/assumptions'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/competitors'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/costs'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/decide'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/economics'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/research'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/execution'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/pitch'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/items/$itemNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DevComponentsRoute: typeof DevComponentsRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_frame': {
      id: '/_authed/_frame'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedFrameRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/welcome': {
      id: '/_authed/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthedWelcomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_frame/account': {
      id: '/_authed/_frame/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedFrameAccountRouteImport
      parentRoute: typeof AuthedFrameRoute
    }
    '/_authed/_frame/admin': {
      id: '/_authed/_frame/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedFrameAdminRouteImport
      parentRoute: typeof AuthedFrameRoute
    }
    '/_authed/_frame/notifications': {
      id: '/_authed/_frame/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedFrameNotificationsRouteImport
      parentRoute: typeof AuthedFrameRoute
    }
    '/_authed/_frame/admin/users': {
      id: '/_authed/_frame/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedFrameAdminUsersRouteImport
      parentRoute: typeof AuthedFrameAdminRoute
    }
    '/_authed/_frame/w/$workspaceId': {
      id: '/_authed/_frame/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdRouteImport
      parentRoute: typeof AuthedFrameRoute
    }
    '/_authed/_frame/w/$workspaceId/': {
      id: '/_authed/_frame/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/decisions': {
      id: '/_authed/_frame/w/$workspaceId/decisions'
      path: '/decisions'
      fullPath: '/w/$workspaceId/decisions'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdDecisionsRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas': {
      id: '/_authed/_frame/w/$workspaceId/ideas'
      path: '/ideas'
      fullPath: '/w/$workspaceId/ideas'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/self-analysis': {
      id: '/_authed/_frame/w/$workspaceId/self-analysis'
      path: '/self-analysis'
      fullPath: '/w/$workspaceId/self-analysis'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdSelfAnalysisRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/settings': {
      id: '/_authed/_frame/w/$workspaceId/settings'
      path: '/settings'
      fullPath: '/w/$workspaceId/settings'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdSettingsRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/team': {
      id: '/_authed/_frame/w/$workspaceId/team'
      path: '/team'
      fullPath: '/w/$workspaceId/team'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdTeamRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ai/export': {
      id: '/_authed/_frame/w/$workspaceId/ai/export'
      path: '/ai/export'
      fullPath: '/w/$workspaceId/ai/export'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdAiExportRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ai/import': {
      id: '/_authed/_frame/w/$workspaceId/ai/import'
      path: '/ai/import'
      fullPath: '/w/$workspaceId/ai/import'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdAiImportRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/': {
      id: '/_authed/_frame/w/$workspaceId/ideas/'
      path: '/'
      fullPath: '/w/$workspaceId/ideas/'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIndexRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId'
      path: '/$ideaId'
      fullPath: '/w/$workspaceId/ideas/$ideaId'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasRoute
    }
    '/_authed/_frame/w/$workspaceId/self-analysis/': {
      id: '/_authed/_frame/w/$workspaceId/self-analysis/'
      path: '/'
      fullPath: '/w/$workspaceId/self-analysis/'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdSelfAnalysisIndexRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdSelfAnalysisRoute
    }
    '/_authed/_frame/w/$workspaceId/self-analysis/$sectionKey': {
      id: '/_authed/_frame/w/$workspaceId/self-analysis/$sectionKey'
      path: '/$sectionKey'
      fullPath: '/w/$workspaceId/self-analysis/$sectionKey'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdSelfAnalysisRoute
    }
    '/_authed/_frame/w/$workspaceId/team/': {
      id: '/_authed/_frame/w/$workspaceId/team/'
      path: '/'
      fullPath: '/w/$workspaceId/team/'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdTeamIndexRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdTeamRoute
    }
    '/_authed/_frame/w/$workspaceId/team/$userId': {
      id: '/_authed/_frame/w/$workspaceId/team/$userId'
      path: '/$userId'
      fullPath: '/w/$workspaceId/team/$userId'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdTeamUserIdRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdTeamRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/'
      path: '/'
      fullPath: '/w/$workspaceId/ideas/$ideaId/'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/assumptions': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/assumptions'
      path: '/assumptions'
      fullPath: '/w/$workspaceId/ideas/$ideaId/assumptions'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/competitors': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/competitors'
      path: '/competitors'
      fullPath: '/w/$workspaceId/ideas/$ideaId/competitors'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/costs': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/costs'
      path: '/costs'
      fullPath: '/w/$workspaceId/ideas/$ideaId/costs'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/decide': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/decide'
      path: '/decide'
      fullPath: '/w/$workspaceId/ideas/$ideaId/decide'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/economics': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/economics'
      path: '/economics'
      fullPath: '/w/$workspaceId/ideas/$ideaId/economics'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/research': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/research'
      path: '/research'
      fullPath: '/w/$workspaceId/ideas/$ideaId/research'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/w/$workspaceId/ideas/$ideaId/plans/$planId'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/questions/$sectionKey': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
      path: '/questions/$sectionKey'
      fullPath: '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/'
      path: '/'
      fullPath: '/w/$workspaceId/ideas/$ideaId/plans/$planId/'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/execution': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/execution'
      path: '/execution'
      fullPath: '/w/$workspaceId/ideas/$ideaId/plans/$planId/execution'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/pitch': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/pitch'
      path: '/pitch'
      fullPath: '/w/$workspaceId/ideas/$ideaId/plans/$planId/pitch'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/items/$itemNo': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/plans/$planId/items/$itemNo'
      path: '/items/$itemNo'
      fullPath: '/w/$workspaceId/ideas/$ideaId/plans/$planId/items/$itemNo'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute
    }
  }
}

interface AuthedFrameAdminRouteChildren {
  AuthedFrameAdminUsersRoute: typeof AuthedFrameAdminUsersRoute
}

const AuthedFrameAdminRouteChildren: AuthedFrameAdminRouteChildren = {
  AuthedFrameAdminUsersRoute: AuthedFrameAdminUsersRoute,
}

const AuthedFrameAdminRouteWithChildren =
  AuthedFrameAdminRoute._addFileChildren(AuthedFrameAdminRouteChildren)

interface AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteChildren {
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRoute
}

const AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteChildren: AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteChildren =
  {
    AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdExecutionRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdPitchRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdIndexRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdItemsItemNoRoute,
  }

const AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteWithChildren =
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute._addFileChildren(
    AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteChildren,
  )

interface AuthedFrameWWorkspaceIdIdeasIdeaIdRouteChildren {
  AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteWithChildren
  AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute
}

const AuthedFrameWWorkspaceIdIdeasIdeaIdRouteChildren: AuthedFrameWWorkspaceIdIdeasIdeaIdRouteChildren =
  {
    AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdAssumptionsRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdCompetitorsRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdResearchRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdPlansPlanIdRouteWithChildren,
    AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute,
  }

const AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren =
  AuthedFrameWWorkspaceIdIdeasIdeaIdRoute._addFileChildren(
    AuthedFrameWWorkspaceIdIdeasIdeaIdRouteChildren,
  )

interface AuthedFrameWWorkspaceIdIdeasRouteChildren {
  AuthedFrameWWorkspaceIdIdeasIdeaIdRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren
  AuthedFrameWWorkspaceIdIdeasIndexRoute: typeof AuthedFrameWWorkspaceIdIdeasIndexRoute
}

const AuthedFrameWWorkspaceIdIdeasRouteChildren: AuthedFrameWWorkspaceIdIdeasRouteChildren =
  {
    AuthedFrameWWorkspaceIdIdeasIdeaIdRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren,
    AuthedFrameWWorkspaceIdIdeasIndexRoute:
      AuthedFrameWWorkspaceIdIdeasIndexRoute,
  }

const AuthedFrameWWorkspaceIdIdeasRouteWithChildren =
  AuthedFrameWWorkspaceIdIdeasRoute._addFileChildren(
    AuthedFrameWWorkspaceIdIdeasRouteChildren,
  )

interface AuthedFrameWWorkspaceIdSelfAnalysisRouteChildren {
  AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRoute: typeof AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRoute
  AuthedFrameWWorkspaceIdSelfAnalysisIndexRoute: typeof AuthedFrameWWorkspaceIdSelfAnalysisIndexRoute
}

const AuthedFrameWWorkspaceIdSelfAnalysisRouteChildren: AuthedFrameWWorkspaceIdSelfAnalysisRouteChildren =
  {
    AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRoute:
      AuthedFrameWWorkspaceIdSelfAnalysisSectionKeyRoute,
    AuthedFrameWWorkspaceIdSelfAnalysisIndexRoute:
      AuthedFrameWWorkspaceIdSelfAnalysisIndexRoute,
  }

const AuthedFrameWWorkspaceIdSelfAnalysisRouteWithChildren =
  AuthedFrameWWorkspaceIdSelfAnalysisRoute._addFileChildren(
    AuthedFrameWWorkspaceIdSelfAnalysisRouteChildren,
  )

interface AuthedFrameWWorkspaceIdTeamRouteChildren {
  AuthedFrameWWorkspaceIdTeamUserIdRoute: typeof AuthedFrameWWorkspaceIdTeamUserIdRoute
  AuthedFrameWWorkspaceIdTeamIndexRoute: typeof AuthedFrameWWorkspaceIdTeamIndexRoute
}

const AuthedFrameWWorkspaceIdTeamRouteChildren: AuthedFrameWWorkspaceIdTeamRouteChildren =
  {
    AuthedFrameWWorkspaceIdTeamUserIdRoute:
      AuthedFrameWWorkspaceIdTeamUserIdRoute,
    AuthedFrameWWorkspaceIdTeamIndexRoute:
      AuthedFrameWWorkspaceIdTeamIndexRoute,
  }

const AuthedFrameWWorkspaceIdTeamRouteWithChildren =
  AuthedFrameWWorkspaceIdTeamRoute._addFileChildren(
    AuthedFrameWWorkspaceIdTeamRouteChildren,
  )

interface AuthedFrameWWorkspaceIdRouteChildren {
  AuthedFrameWWorkspaceIdDecisionsRoute: typeof AuthedFrameWWorkspaceIdDecisionsRoute
  AuthedFrameWWorkspaceIdIdeasRoute: typeof AuthedFrameWWorkspaceIdIdeasRouteWithChildren
  AuthedFrameWWorkspaceIdSelfAnalysisRoute: typeof AuthedFrameWWorkspaceIdSelfAnalysisRouteWithChildren
  AuthedFrameWWorkspaceIdSettingsRoute: typeof AuthedFrameWWorkspaceIdSettingsRoute
  AuthedFrameWWorkspaceIdTeamRoute: typeof AuthedFrameWWorkspaceIdTeamRouteWithChildren
  AuthedFrameWWorkspaceIdIndexRoute: typeof AuthedFrameWWorkspaceIdIndexRoute
  AuthedFrameWWorkspaceIdAiExportRoute: typeof AuthedFrameWWorkspaceIdAiExportRoute
  AuthedFrameWWorkspaceIdAiImportRoute: typeof AuthedFrameWWorkspaceIdAiImportRoute
}

const AuthedFrameWWorkspaceIdRouteChildren: AuthedFrameWWorkspaceIdRouteChildren =
  {
    AuthedFrameWWorkspaceIdDecisionsRoute:
      AuthedFrameWWorkspaceIdDecisionsRoute,
    AuthedFrameWWorkspaceIdIdeasRoute:
      AuthedFrameWWorkspaceIdIdeasRouteWithChildren,
    AuthedFrameWWorkspaceIdSelfAnalysisRoute:
      AuthedFrameWWorkspaceIdSelfAnalysisRouteWithChildren,
    AuthedFrameWWorkspaceIdSettingsRoute: AuthedFrameWWorkspaceIdSettingsRoute,
    AuthedFrameWWorkspaceIdTeamRoute:
      AuthedFrameWWorkspaceIdTeamRouteWithChildren,
    AuthedFrameWWorkspaceIdIndexRoute: AuthedFrameWWorkspaceIdIndexRoute,
    AuthedFrameWWorkspaceIdAiExportRoute: AuthedFrameWWorkspaceIdAiExportRoute,
    AuthedFrameWWorkspaceIdAiImportRoute: AuthedFrameWWorkspaceIdAiImportRoute,
  }

const AuthedFrameWWorkspaceIdRouteWithChildren =
  AuthedFrameWWorkspaceIdRoute._addFileChildren(
    AuthedFrameWWorkspaceIdRouteChildren,
  )

interface AuthedFrameRouteChildren {
  AuthedFrameAccountRoute: typeof AuthedFrameAccountRoute
  AuthedFrameAdminRoute: typeof AuthedFrameAdminRouteWithChildren
  AuthedFrameNotificationsRoute: typeof AuthedFrameNotificationsRoute
  AuthedFrameWWorkspaceIdRoute: typeof AuthedFrameWWorkspaceIdRouteWithChildren
}

const AuthedFrameRouteChildren: AuthedFrameRouteChildren = {
  AuthedFrameAccountRoute: AuthedFrameAccountRoute,
  AuthedFrameAdminRoute: AuthedFrameAdminRouteWithChildren,
  AuthedFrameNotificationsRoute: AuthedFrameNotificationsRoute,
  AuthedFrameWWorkspaceIdRoute: AuthedFrameWWorkspaceIdRouteWithChildren,
}

const AuthedFrameRouteWithChildren = AuthedFrameRoute._addFileChildren(
  AuthedFrameRouteChildren,
)

interface AuthedRouteChildren {
  AuthedFrameRoute: typeof AuthedFrameRouteWithChildren
  AuthedWelcomeRoute: typeof AuthedWelcomeRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedFrameRoute: AuthedFrameRouteWithChildren,
  AuthedWelcomeRoute: AuthedWelcomeRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DevComponentsRoute: DevComponentsRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
