/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthedFrameRouteImport } from './routes/_authed/_frame'
import { Route as AuthedWelcomeRouteImport } from './routes/_authed/welcome'
import { Route as DevComponentsRouteImport } from './routes/dev.components'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthedFrameAccountRouteImport } from './routes/_authed/_frame/account'
import { Route as AuthedFrameWWorkspaceIdRouteImport } from './routes/_authed/_frame/w.$workspaceId'
import { Route as AuthedFrameWWorkspaceIdIndexRouteImport } from './routes/_authed/_frame/w.$workspaceId.index'
import { Route as AuthedFrameWWorkspaceIdIdeasRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas'
import { Route as AuthedFrameWWorkspaceIdAiExportRouteImport } from './routes/_authed/_frame/w.$workspaceId.ai.export'
import { Route as AuthedFrameWWorkspaceIdAiImportRouteImport } from './routes/_authed/_frame/w.$workspaceId.ai.import'
import { Route as AuthedFrameWWorkspaceIdIdeasIndexRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.index'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.index'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.costs'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.decide'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.economics'
import { Route as AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRouteImport } from './routes/_authed/_frame/w.$workspaceId.ideas.$ideaId.questions.$sectionKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedFrameRoute = AuthedFrameRouteImport.update({
  id: '/_frame',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWelcomeRoute = AuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedRoute,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedFrameAccountRoute = AuthedFrameAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedFrameRoute,
} as any)
const AuthedFrameWWorkspaceIdRoute = AuthedFrameWWorkspaceIdRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => AuthedFrameRoute,
} as any)
const AuthedFrameWWorkspaceIdIndexRoute =
  AuthedFrameWWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasRoute =
  AuthedFrameWWorkspaceIdIdeasRouteImport.update({
    id: '/ideas',
    path: '/ideas',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdAiExportRoute =
  AuthedFrameWWorkspaceIdAiExportRouteImport.update({
    id: '/ai/export',
    path: '/ai/export',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdAiImportRoute =
  AuthedFrameWWorkspaceIdAiImportRouteImport.update({
    id: '/ai/import',
    path: '/ai/import',
    getParentRoute: () => AuthedFrameWWorkspaceIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIndexRoute =
  AuthedFrameWWorkspaceIdIdeasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdRouteImport.update({
    id: '/$ideaId',
    path: '/$ideaId',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRouteImport.update({
    id: '/costs',
    path: '/costs',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRouteImport.update({
    id: '/decide',
    path: '/decide',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRouteImport.update({
    id: '/economics',
    path: '/economics',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)
const AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute =
  AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRouteImport.update({
    id: '/questions/$sectionKey',
    path: '/questions/$sectionKey',
    getParentRoute: () => AuthedFrameWWorkspaceIdIdeasIdeaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/dev/components': typeof DevComponentsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/account': typeof AuthedFrameAccountRoute
  '/w/$workspaceId': typeof AuthedFrameWWorkspaceIdRouteWithChildren
  '/w/$workspaceId/ideas': typeof AuthedFrameWWorkspaceIdIdeasRouteWithChildren
  '/w/$workspaceId/': typeof AuthedFrameWWorkspaceIdIndexRoute
  '/w/$workspaceId/ai/export': typeof AuthedFrameWWorkspaceIdAiExportRoute
  '/w/$workspaceId/ai/import': typeof AuthedFrameWWorkspaceIdAiImportRoute
  '/w/$workspaceId/ideas/$ideaId': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren
  '/w/$workspaceId/ideas/': typeof AuthedFrameWWorkspaceIdIdeasIndexRoute
  '/w/$workspaceId/ideas/$ideaId/costs': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute
  '/w/$workspaceId/ideas/$ideaId/decide': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute
  '/w/$workspaceId/ideas/$ideaId/economics': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute
  '/w/$workspaceId/ideas/$ideaId/': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute
  '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/dev/components': typeof DevComponentsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/account': typeof AuthedFrameAccountRoute
  '/w/$workspaceId': typeof AuthedFrameWWorkspaceIdIndexRoute
  '/w/$workspaceId/ai/export': typeof AuthedFrameWWorkspaceIdAiExportRoute
  '/w/$workspaceId/ai/import': typeof AuthedFrameWWorkspaceIdAiImportRoute
  '/w/$workspaceId/ideas': typeof AuthedFrameWWorkspaceIdIdeasIndexRoute
  '/w/$workspaceId/ideas/$ideaId/costs': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute
  '/w/$workspaceId/ideas/$ideaId/decide': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute
  '/w/$workspaceId/ideas/$ideaId/economics': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute
  '/w/$workspaceId/ideas/$ideaId': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute
  '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/_frame': typeof AuthedFrameRouteWithChildren
  '/_authed/welcome': typeof AuthedWelcomeRoute
  '/dev/components': typeof DevComponentsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authed/_frame/account': typeof AuthedFrameAccountRoute
  '/_authed/_frame/w/$workspaceId': typeof AuthedFrameWWorkspaceIdRouteWithChildren
  '/_authed/_frame/w/$workspaceId/ideas': typeof AuthedFrameWWorkspaceIdIdeasRouteWithChildren
  '/_authed/_frame/w/$workspaceId/': typeof AuthedFrameWWorkspaceIdIndexRoute
  '/_authed/_frame/w/$workspaceId/ai/export': typeof AuthedFrameWWorkspaceIdAiExportRoute
  '/_authed/_frame/w/$workspaceId/ai/import': typeof AuthedFrameWWorkspaceIdAiImportRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren
  '/_authed/_frame/w/$workspaceId/ideas/': typeof AuthedFrameWWorkspaceIdIdeasIndexRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/costs': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/decide': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/economics': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute
  '/_authed/_frame/w/$workspaceId/ideas/$ideaId/questions/$sectionKey': typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/welcome'
    | '/dev/components'
    | '/invite/$token'
    | '/account'
    | '/w/$workspaceId'
    | '/w/$workspaceId/ideas'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/ai/export'
    | '/w/$workspaceId/ai/import'
    | '/w/$workspaceId/ideas/$ideaId'
    | '/w/$workspaceId/ideas/'
    | '/w/$workspaceId/ideas/$ideaId/costs'
    | '/w/$workspaceId/ideas/$ideaId/decide'
    | '/w/$workspaceId/ideas/$ideaId/economics'
    | '/w/$workspaceId/ideas/$ideaId/'
    | '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/welcome'
    | '/dev/components'
    | '/invite/$token'
    | '/account'
    | '/w/$workspaceId'
    | '/w/$workspaceId/ai/export'
    | '/w/$workspaceId/ai/import'
    | '/w/$workspaceId/ideas'
    | '/w/$workspaceId/ideas/$ideaId/costs'
    | '/w/$workspaceId/ideas/$ideaId/decide'
    | '/w/$workspaceId/ideas/$ideaId/economics'
    | '/w/$workspaceId/ideas/$ideaId'
    | '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authed/_frame'
    | '/_authed/welcome'
    | '/dev/components'
    | '/invite/$token'
    | '/_authed/_frame/account'
    | '/_authed/_frame/w/$workspaceId'
    | '/_authed/_frame/w/$workspaceId/ideas'
    | '/_authed/_frame/w/$workspaceId/'
    | '/_authed/_frame/w/$workspaceId/ai/export'
    | '/_authed/_frame/w/$workspaceId/ai/import'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId'
    | '/_authed/_frame/w/$workspaceId/ideas/'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/costs'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/decide'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/economics'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/'
    | '/_authed/_frame/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DevComponentsRoute: typeof DevComponentsRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_frame': {
      id: '/_authed/_frame'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedFrameRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/welcome': {
      id: '/_authed/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthedWelcomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_frame/account': {
      id: '/_authed/_frame/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedFrameAccountRouteImport
      parentRoute: typeof AuthedFrameRoute
    }
    '/_authed/_frame/w/$workspaceId': {
      id: '/_authed/_frame/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdRouteImport
      parentRoute: typeof AuthedFrameRoute
    }
    '/_authed/_frame/w/$workspaceId/': {
      id: '/_authed/_frame/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas': {
      id: '/_authed/_frame/w/$workspaceId/ideas'
      path: '/ideas'
      fullPath: '/w/$workspaceId/ideas'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ai/export': {
      id: '/_authed/_frame/w/$workspaceId/ai/export'
      path: '/ai/export'
      fullPath: '/w/$workspaceId/ai/export'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdAiExportRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ai/import': {
      id: '/_authed/_frame/w/$workspaceId/ai/import'
      path: '/ai/import'
      fullPath: '/w/$workspaceId/ai/import'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdAiImportRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/': {
      id: '/_authed/_frame/w/$workspaceId/ideas/'
      path: '/'
      fullPath: '/w/$workspaceId/ideas/'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIndexRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId'
      path: '/$ideaId'
      fullPath: '/w/$workspaceId/ideas/$ideaId'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/'
      path: '/'
      fullPath: '/w/$workspaceId/ideas/$ideaId/'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/costs': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/costs'
      path: '/costs'
      fullPath: '/w/$workspaceId/ideas/$ideaId/costs'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/decide': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/decide'
      path: '/decide'
      fullPath: '/w/$workspaceId/ideas/$ideaId/decide'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/economics': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/economics'
      path: '/economics'
      fullPath: '/w/$workspaceId/ideas/$ideaId/economics'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
    '/_authed/_frame/w/$workspaceId/ideas/$ideaId/questions/$sectionKey': {
      id: '/_authed/_frame/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
      path: '/questions/$sectionKey'
      fullPath: '/w/$workspaceId/ideas/$ideaId/questions/$sectionKey'
      preLoaderRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRouteImport
      parentRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRoute
    }
  }
}

interface AuthedFrameWWorkspaceIdIdeasIdeaIdRouteChildren {
  AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute
  AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute
}

const AuthedFrameWWorkspaceIdIdeasIdeaIdRouteChildren: AuthedFrameWWorkspaceIdIdeasIdeaIdRouteChildren =
  {
    AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdCostsRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdDecideRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdEconomicsRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdIndexRoute,
    AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdQuestionsSectionKeyRoute,
  }

const AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren =
  AuthedFrameWWorkspaceIdIdeasIdeaIdRoute._addFileChildren(
    AuthedFrameWWorkspaceIdIdeasIdeaIdRouteChildren,
  )

interface AuthedFrameWWorkspaceIdIdeasRouteChildren {
  AuthedFrameWWorkspaceIdIdeasIdeaIdRoute: typeof AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren
  AuthedFrameWWorkspaceIdIdeasIndexRoute: typeof AuthedFrameWWorkspaceIdIdeasIndexRoute
}

const AuthedFrameWWorkspaceIdIdeasRouteChildren: AuthedFrameWWorkspaceIdIdeasRouteChildren =
  {
    AuthedFrameWWorkspaceIdIdeasIdeaIdRoute:
      AuthedFrameWWorkspaceIdIdeasIdeaIdRouteWithChildren,
    AuthedFrameWWorkspaceIdIdeasIndexRoute:
      AuthedFrameWWorkspaceIdIdeasIndexRoute,
  }

const AuthedFrameWWorkspaceIdIdeasRouteWithChildren =
  AuthedFrameWWorkspaceIdIdeasRoute._addFileChildren(
    AuthedFrameWWorkspaceIdIdeasRouteChildren,
  )

interface AuthedFrameWWorkspaceIdRouteChildren {
  AuthedFrameWWorkspaceIdIdeasRoute: typeof AuthedFrameWWorkspaceIdIdeasRouteWithChildren
  AuthedFrameWWorkspaceIdIndexRoute: typeof AuthedFrameWWorkspaceIdIndexRoute
  AuthedFrameWWorkspaceIdAiExportRoute: typeof AuthedFrameWWorkspaceIdAiExportRoute
  AuthedFrameWWorkspaceIdAiImportRoute: typeof AuthedFrameWWorkspaceIdAiImportRoute
}

const AuthedFrameWWorkspaceIdRouteChildren: AuthedFrameWWorkspaceIdRouteChildren =
  {
    AuthedFrameWWorkspaceIdIdeasRoute:
      AuthedFrameWWorkspaceIdIdeasRouteWithChildren,
    AuthedFrameWWorkspaceIdIndexRoute: AuthedFrameWWorkspaceIdIndexRoute,
    AuthedFrameWWorkspaceIdAiExportRoute: AuthedFrameWWorkspaceIdAiExportRoute,
    AuthedFrameWWorkspaceIdAiImportRoute: AuthedFrameWWorkspaceIdAiImportRoute,
  }

const AuthedFrameWWorkspaceIdRouteWithChildren =
  AuthedFrameWWorkspaceIdRoute._addFileChildren(
    AuthedFrameWWorkspaceIdRouteChildren,
  )

interface AuthedFrameRouteChildren {
  AuthedFrameAccountRoute: typeof AuthedFrameAccountRoute
  AuthedFrameWWorkspaceIdRoute: typeof AuthedFrameWWorkspaceIdRouteWithChildren
}

const AuthedFrameRouteChildren: AuthedFrameRouteChildren = {
  AuthedFrameAccountRoute: AuthedFrameAccountRoute,
  AuthedFrameWWorkspaceIdRoute: AuthedFrameWWorkspaceIdRouteWithChildren,
}

const AuthedFrameRouteWithChildren = AuthedFrameRoute._addFileChildren(
  AuthedFrameRouteChildren,
)

interface AuthedRouteChildren {
  AuthedFrameRoute: typeof AuthedFrameRouteWithChildren
  AuthedWelcomeRoute: typeof AuthedWelcomeRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedFrameRoute: AuthedFrameRouteWithChildren,
  AuthedWelcomeRoute: AuthedWelcomeRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DevComponentsRoute: DevComponentsRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
