import {
  isResolved,
  type Leaf,
  type Resolved,
  resolveSubtree,
  type Scale,
  type TokenMap,
  type Tree,
} from "./dtcg";

const HEADER = `/**
 * Generated by \`make tokens\` from docs/06_design-tokens.json. Do not edit by hand.
 */
`;

type Out = string | number | OutObject | string[] | number[];
interface OutObject {
  [key: string]: Out;
}

function mapTree(
  tree: Tree,
  convert: (node: Resolved, path: string[]) => Out,
  path: string[] = [],
): OutObject {
  const out: OutObject = {};
  for (const [key, node] of Object.entries(tree)) {
    out[key] = isResolved(node)
      ? convert(node, [...path, key])
      : mapTree(node as Tree, convert, [...path, key]);
  }
  return out;
}

function render(
  name: string,
  value: unknown,
  { asConst = false, spread = "", doc = "" } = {},
): string {
  const body = JSON.stringify(value, null, 2);
  const withSpread = spread ? body.replace(/^\{/, `{\n  ...${spread},`) : body;
  const comment = doc ? `/** ${doc} */\n` : "";
  return `${comment}export const ${name} = ${withSpread}${asConst ? " as const" : ""};\n`;
}

function field(node: Resolved, name: string): Leaf {
  if (node.kind !== "composite") throw new Error(`expected a composite token, got ${node.kind}`);
  const leaf = node.fields[name];
  if (!leaf) throw new Error(`composite token has no field "${name}"`);
  return leaf;
}

function expectKind<K extends Leaf["kind"]>(
  leaf: Leaf,
  kind: K,
  where: string,
): Extract<Leaf, { kind: K }> {
  if (leaf.kind !== kind) throw new Error(`${where}: expected ${kind}, got ${leaf.kind}`);
  return leaf as Extract<Leaf, { kind: K }>;
}

function hexToRgb(hex: string): [number, number, number] {
  return [1, 3, 5].map((i) => Number.parseInt(hex.slice(i, i + 2), 16)) as [number, number, number];
}

function colorString(color: Extract<Leaf, { kind: "color" }>): string {
  if (color.alpha === 1) return color.hex;
  const [r, g, b] = hexToRgb(color.hex);
  return `rgba(${r}, ${g}, ${b}, ${color.alpha})`;
}

// ---- Web (vanilla-extract) -------------------------------------------------

function cssFontFamily(names: string[]): string {
  return names.map((n) => (/\s/.test(n) ? `"${n}"` : n)).join(", ");
}

function cssLeaf(leaf: Leaf): string {
  switch (leaf.kind) {
    case "color":
      return colorString(leaf);
    case "dimension":
      // Font sizes are rem so the browser's text-size setting scales them.
      return leaf.fontSize ? `${leaf.px / 16}rem` : `${leaf.px}px`;
    case "duration":
      return `${leaf.ms}ms`;
    case "number":
      return String(leaf.value);
    case "fontFamily":
      return cssFontFamily(leaf.names);
    case "cubicBezier":
      return `cubic-bezier(${leaf.points.join(", ")})`;
    case "string":
      return leaf.value;
  }
}

function cssNode(node: Resolved): string | OutObject {
  if (node.kind !== "composite") return cssLeaf(node);
  if (node.type === "typography") {
    const out: OutObject = {};
    for (const [name, leaf] of Object.entries(node.fields)) out[name] = cssLeaf(leaf);
    return out;
  }
  if (node.type === "shadow") {
    const dim = (name: string) =>
      cssLeaf(expectKind(field(node, name), "dimension", `shadow.${name}`));
    const color = cssLeaf(expectKind(field(node, "color"), "color", "shadow.color"));
    return `${dim("offsetX")} ${dim("offsetY")} ${dim("blur")} ${dim("spread")} ${color}`;
  }
  const duration = cssLeaf(expectKind(field(node, "duration"), "duration", "transition.duration"));
  const delay = cssLeaf(expectKind(field(node, "delay"), "duration", "transition.delay"));
  const timing = cssLeaf(
    expectKind(field(node, "timingFunction"), "cubicBezier", "transition.timingFunction"),
  );
  return `${duration} ${timing} ${delay}`;
}

const webTree = (tokens: TokenMap, prefix: string, scale: Scale) =>
  mapTree(resolveSubtree(tokens, prefix, scale), cssNode);

export function emitWeb(tokens: TokenMap): string {
  const section = (prefix: string, scale: Scale = "medium") => webTree(tokens, prefix, scale);
  const base = {
    space: section("semantic.space"),
    font: section("semantic.font"),
    radius: section("semantic.radius"),
    "border-width": section("semantic.border-width"),
    breakpoint: section("semantic.breakpoint"),
    layout: section("semantic.layout"),
    icon: section("semantic.icon"),
    motion: section("semantic.motion"),
    print: section("semantic.print"),
  };
  const colors = (mode: "light" | "dark") => ({
    color: section(`semantic.color.${mode}`),
    shadow: section(`semantic.shadow.${mode}`),
  });
  const scaled = (scale: Scale) => ({
    scale: section(`semantic.scale.${scale}`),
    typography: section("semantic.typography", scale),
    density: section("semantic.density", scale),
  });
  const breakpoints = mapTree(resolveSubtree(tokens, "semantic.breakpoint", "medium"), (node) => {
    if (node.kind !== "dimension") throw new Error("breakpoint must be a dimension");
    return node.px;
  });

  return [
    HEADER,
    `import {
  assignVars,
  createGlobalTheme,
  createGlobalThemeContract,
  globalStyle,
} from "@vanilla-extract/css";

const varName = (_value: string | null, path: string[]) => \`moonx-\${path.join("-")}\`;
`,
    render("base", base),
    render("colorLight", colors("light")),
    render("colorDark", colors("dark")),
    render("scaleMedium", scaled("medium")),
    render("scaleLarge", scaled("large")),
    `
const baseVars = createGlobalThemeContract(base, varName);
const colorVars = createGlobalThemeContract(colorLight, varName);
const scaleVars = createGlobalThemeContract(scaleMedium, varName);

createGlobalTheme(":root", baseVars, base);

// Light is the default. Dark follows the OS unless <html data-theme="light"> pins light.
globalStyle(":root", { vars: assignVars(colorVars, colorLight) });
globalStyle(':root[data-theme="dark"]', { vars: assignVars(colorVars, colorDark) });
globalStyle(':root:not([data-theme="light"])', {
  "@media": { "(prefers-color-scheme: dark)": { vars: assignVars(colorVars, colorDark) } },
});

// Medium is the default. Touch devices take large unless <html data-scale="medium"> pins medium.
globalStyle(":root", { vars: assignVars(scaleVars, scaleMedium) });
globalStyle(':root[data-scale="large"]', { vars: assignVars(scaleVars, scaleLarge) });
globalStyle(':root:not([data-scale="medium"])', {
  "@media": { "(pointer: coarse)": { vars: assignVars(scaleVars, scaleLarge) } },
});

/** Typed references to the CSS variables. Components read semantic tokens only through this. */
export const vars = { ...baseVars, ...colorVars, ...scaleVars };
`,
    render("breakpoints", breakpoints, {
      asConst: true,
      doc: "Minimum widths in px, for media queries (CSS variables cannot be used there).",
    }),
  ].join("\n");
}

// ---- Native (Unistyles) ----------------------------------------------------

// RN takes the OS default sans-serif when no family is given, and has no single monospace name
// (06: primitive.font.family.sans / mono descriptions; semantic.native.font names the per-OS mono).
const NATIVE_FONT_ROLE: Record<string, "display" | "body" | "mono"> = {
  "primitive.font.family.display": "display",
  "primitive.font.family.sans": "body",
  "primitive.font.family.mono": "mono",
};

function nativeLeaf(leaf: Leaf): string | number | number[] {
  switch (leaf.kind) {
    case "color":
      return colorString(leaf);
    case "dimension":
      return leaf.px;
    case "duration":
      return leaf.ms;
    case "number":
      return leaf.value;
    case "cubicBezier":
      return leaf.points;
    case "string":
      return leaf.value;
    case "fontFamily":
      throw new Error("font families are emitted through fontFamily and fontRole");
  }
}

function nativeNode(node: Resolved, path: string[]): Out {
  if (node.kind === "fontFamily") {
    const role = NATIVE_FONT_ROLE[node.source];
    if (!role) throw new Error(`${path.join(".")}: no native font role for ${node.source}`);
    return role;
  }
  if (node.kind !== "composite") return nativeLeaf(node);
  if (node.type === "typography") {
    const family = expectKind(field(node, "fontFamily"), "fontFamily", "typography.fontFamily");
    const fontRole = NATIVE_FONT_ROLE[family.source];
    if (!fontRole) throw new Error(`${path.join(".")}: no native font role for ${family.source}`);
    const fontSize = expectKind(field(node, "fontSize"), "dimension", "typography.fontSize").px;
    const lineHeight = expectKind(
      field(node, "lineHeight"),
      "number",
      "typography.lineHeight",
    ).value;
    const out: OutObject = {
      fontRole,
      fontSize,
      fontWeight: String(
        expectKind(field(node, "fontWeight"), "number", "typography.fontWeight").value,
      ),
      letterSpacing: expectKind(
        field(node, "letterSpacing"),
        "dimension",
        "typography.letterSpacing",
      ).px,
      lineHeight: Math.round(fontSize * lineHeight * 100) / 100,
    };
    if (node.fields.fontVariantNumeric) {
      out.fontVariant = [
        expectKind(node.fields.fontVariantNumeric, "string", "typography.fontVariantNumeric").value,
      ];
    }
    return out;
  }
  if (node.type === "shadow") {
    const num = (name: string) => expectKind(field(node, name), "dimension", `shadow.${name}`).px;
    return {
      color: colorString(expectKind(field(node, "color"), "color", "shadow.color")),
      offsetX: num("offsetX"),
      offsetY: num("offsetY"),
      blur: num("blur"),
      spread: num("spread"),
    };
  }
  return {
    duration: expectKind(field(node, "duration"), "duration", "transition.duration").ms,
    delay: expectKind(field(node, "delay"), "duration", "transition.delay").ms,
    easing: expectKind(field(node, "timingFunction"), "cubicBezier", "transition.timingFunction")
      .points,
  };
}

export function emitNative(tokens: TokenMap): string {
  const section = (prefix: string, scale: Scale = "large") =>
    mapTree(resolveSubtree(tokens, prefix, scale), nativeNode);
  const familyTree = resolveSubtree(tokens, "semantic.font.family", "large");
  const display = familyTree.display;
  if (!display || !isResolved(display) || display.kind !== "fontFamily") {
    throw new Error("semantic.font.family.display must resolve to a font family");
  }
  const nativeMono = (name: "mono-ios" | "mono-android") => {
    const leaf = resolveSubtree(tokens, "semantic.native.font", "large")[name];
    if (!leaf || !isResolved(leaf) || leaf.kind !== "fontFamily") {
      throw new Error(`semantic.native.font.${name} must resolve to a font family`);
    }
    return leaf.names[0];
  };
  const fontFamily = {
    display: display.names[0],
    mono: { ios: nativeMono("mono-ios"), android: nativeMono("mono-android") },
  };

  const shared = {
    space: section("semantic.space"),
    radius: section("semantic.radius"),
    "border-width": section("semantic.border-width"),
    layout: section("semantic.layout"),
    icon: section("semantic.icon"),
    motion: section("semantic.motion"),
    scale: section("semantic.scale.large"),
    typography: section("semantic.typography"),
    density: section("semantic.density"),
  };
  const colors = (mode: "light" | "dark") => ({
    color: section(`semantic.color.${mode}`),
    shadow: section(`semantic.shadow.${mode}`),
  });
  const breakpointTree = mapTree(
    resolveSubtree(tokens, "semantic.breakpoint", "large"),
    nativeNode,
  );

  return [
    HEADER,
    `/**
 * Typography entries name a \`fontRole\` instead of a family. "display" is \`fontFamily.display\`,
 * "body" takes the OS default sans-serif (no fontFamily), "mono" is \`fontFamily.mono\` per platform.
 * The native scale is large (touch targets); the themes carry no medium values.
 */
`,
    render("fontFamily", fontFamily),
    render("breakpoints", breakpointTree, { asConst: true }),
    `const shared = ${JSON.stringify(shared, null, 2)};\n`,
    render("lightTheme", colors("light"), { spread: "shared" }),
    render("darkTheme", colors("dark"), { spread: "shared" }),
    "export const themes = { light: lightTheme, dark: darkTheme };\n",
    "export type Theme = typeof lightTheme;\n",
  ].join("\n");
}

// ---- PDF (react-pdf) -------------------------------------------------------

function printNode(node: Resolved, path: string[]): Out {
  if (node.kind === "fontFamily") return node.names;
  if (node.kind === "color") {
    if (node.alpha !== 1) throw new Error(`${path.join(".")}: PDF colors must be opaque`);
    return node.hex;
  }
  if (node.kind === "composite") {
    if (node.type !== "typography")
      throw new Error(`${path.join(".")}: unsupported print composite`);
    const out: OutObject = {};
    for (const [name, leaf] of Object.entries(node.fields))
      out[name] = printNode(leaf, [...path, name]);
    return out;
  }
  return nativeLeaf(node);
}

export function emitPrint(tokens: TokenMap): string {
  // 1px = 1pt in react-pdf; the print values are light only (design-spec 6.14)
  const print = mapTree(resolveSubtree(tokens, "semantic.print", "medium"), printNode);
  return [HEADER, render("print", print)].join("\n");
}
